export const basic_menus = [
  {
    "id": "120",
    "pid": 0,
    "title": "工作台",
    "icon": "appstore-o",
    "url": "home",
    "file_path": "home",
    "params": ":org",
    "node": "#",
    "sort": 0,
    "status": 1,
    "create_by": 0,
    "create_at": "2018-09-30 16:30:01",
    "is_inner": false,
    "values": "",
    "show_slider": 0,
    "statusText": "使用中",
    "innerText": "导航",
    "fullUrl": "home"
  },
  {
    "id": "121",
    "pid": 0,
    "title": "项目管理",
    "icon": "project",
    "url": "#",
    "file_path": "#",
    "params": "",
    "node": "#",
    "sort": 0,
    "status": 1,
    "create_by": 0,
    "create_at": "0000-00-00 00:00:00",
    "is_inner": false,
    "values": "",
    "show_slider": 1,
    "statusText": "使用中",
    "innerText": "导航",
    "fullUrl": "#",
    "children": [
      {
        "id": "122",
        "pid": 121,
        "title": "项目列表",
        "icon": "branches",
        "url": "#",
        "file_path": "#",
        "params": "",
        "node": "#",
        "sort": 0,
        "status": 1,
        "create_by": 0,
        "create_at": "0000-00-00 00:00:00",
        "is_inner": false,
        "values": "",
        "show_slider": 1,
        "statusText": "使用中",
        "innerText": "导航",
        "fullUrl": "#",
        "children": [
          {
            "id": "151",
            "pid": 122,
            "title": "我的项目",
            "icon": "",
            "url": "project/list",
            "file_path": "project/list",
            "params": ":type",
            "node": "project/project/index",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "all",
            "show_slider": 1,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "project/list/all"
          },
          {
            "id": "163",
            "pid": 122,
            "title": "项目分析",
            "icon": "",
            "url": "project/analysis",
            "file_path": "project/analysis",
            "params": "",
            "node": "project/index/info",
            "sort": 5,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": false,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "project/analysis"
          },
          {
            "id": "155",
            "pid": 122,
            "title": "我的收藏",
            "icon": "",
            "url": "project/list",
            "file_path": "project/list",
            "params": ":type",
            "node": "project/project/index",
            "sort": 10,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "collect",
            "show_slider": 1,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "project/list/collect"
          },
          {
            "id": "159",
            "pid": 122,
            "title": "已归档项目",
            "icon": "",
            "url": "project/archive",
            "file_path": "project/archive",
            "params": "",
            "node": "project/project/index",
            "sort": 10,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": false,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "project/archive"
          },
          {
            "id": "152",
            "pid": 122,
            "title": "回收站",
            "icon": "",
            "url": "project/recycle",
            "file_path": "project/recycle",
            "params": "",
            "node": "project/project/index",
            "sort": 20,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "project/recycle"
          },
          {
            "id": "127",
            "pid": 122,
            "title": "我的组织",
            "icon": "",
            "url": "organization",
            "file_path": "organization",
            "params": "",
            "node": "project/organization/index",
            "sort": 30,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "organization"
          }
        ]
      },
      {
        "id": "156",
        "pid": 121,
        "title": "基础设置",
        "icon": "experiment",
        "url": "#",
        "file_path": "#",
        "params": "",
        "node": "#",
        "sort": 0,
        "status": 1,
        "create_by": 0,
        "create_at": "0000-00-00 00:00:00",
        "is_inner": false,
        "values": "",
        "show_slider": 0,
        "statusText": "使用中",
        "innerText": "导航",
        "fullUrl": "#",
        "children": [
          {
            "id": "157",
            "pid": 156,
            "title": "项目模板",
            "icon": "",
            "url": "project/template",
            "file_path": "project/template",
            "params": "",
            "node": "project/project_template/index",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "project/template"
          },
          {
            "id": "158",
            "pid": 156,
            "title": "项目列表模板",
            "icon": "",
            "url": "project/template/taskStages",
            "file_path": "project/template/taskStages",
            "params": ":code",
            "node": "project/task_stages_template/index",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "project/template/taskStages"
          }
        ]
      },
      {
        "id": "153",
        "pid": 121,
        "title": "项目空间",
        "icon": "heat-map",
        "url": "project/space/task",
        "file_path": "project/space/task",
        "params": ":code",
        "node": "#",
        "sort": 20,
        "status": 1,
        "create_by": 0,
        "create_at": "0000-00-00 00:00:00",
        "is_inner": true,
        "values": "",
        "show_slider": 1,
        "statusText": "使用中",
        "innerText": "内页",
        "fullUrl": "project/space/task",
        "children": [
          {
            "id": "154",
            "pid": 153,
            "title": "任务详情",
            "icon": "",
            "url": "project/space/task/:code/detail",
            "file_path": "project/space/taskdetail",
            "params": ":code",
            "node": "project/task/read",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "project/space/task/:code/detail"
          },
          {
            "id": "162",
            "pid": 153,
            "title": "项目文件",
            "icon": "",
            "url": "project/space/files",
            "file_path": "project/space/files",
            "params": ":code",
            "node": "project/index/info",
            "sort": 10,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "project/space/files"
          },
          {
            "id": "161",
            "pid": 153,
            "title": "项目概况",
            "icon": "",
            "url": "project/space/overview",
            "file_path": "project/space/overview",
            "params": ":code",
            "node": "project/index/info",
            "sort": 20,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "project/space/overview"
          },
          {
            "id": "168",
            "pid": 153,
            "title": "版本管理",
            "icon": "",
            "url": "project/space/features",
            "file_path": "project/space/features",
            "params": ":code",
            "node": "project/index/info",
            "sort": 20,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "project/space/features"
          }
        ]
      }
    ]
  },
  {
    "id": "160",
    "pid": 0,
    "title": "团队成员",
    "icon": "team",
    "url": "#",
    "file_path": "#",
    "params": "",
    "node": "#",
    "sort": 0,
    "status": 1,
    "create_by": 0,
    "create_at": null,
    "is_inner": true,
    "values": "",
    "show_slider": 0,
    "statusText": "使用中",
    "innerText": "内页",
    "fullUrl": "#",
    "children": [
      {
        "id": "164",
        "pid": 160,
        "title": "团队成员",
        "icon": "",
        "url": "#",
        "file_path": "#",
        "params": "",
        "node": "#",
        "sort": 0,
        "status": 1,
        "create_by": 0,
        "create_at": null,
        "is_inner": true,
        "values": "",
        "show_slider": 0,
        "statusText": "使用中",
        "innerText": "内页",
        "fullUrl": "#",
        "children": [
          {
            "id": "166",
            "pid": 164,
            "title": "团队成员",
            "icon": "",
            "url": "members",
            "file_path": "members",
            "params": "",
            "node": "project/department/index",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "members"
          },
          {
            "id": "167",
            "pid": 164,
            "title": "成员信息",
            "icon": "",
            "url": "members/profile",
            "file_path": "members/profile",
            "params": ":code",
            "node": "project/department/read",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": null,
            "is_inner": true,
            "values": "",
            "show_slider": 0,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "members/profile"
          }
        ]
      }
    ]
  },
  {
    "id": "124",
    "pid": 0,
    "title": "系统设置",
    "icon": "setting",
    "url": "#",
    "file_path": "#",
    "params": "",
    "node": "#",
    "sort": 100,
    "status": 1,
    "create_by": 0,
    "create_at": "0000-00-00 00:00:00",
    "is_inner": false,
    "values": "",
    "show_slider": 1,
    "statusText": "使用中",
    "innerText": "导航",
    "fullUrl": "#",
    "children": [
      {
        "id": "148",
        "pid": 124,
        "title": "个人管理",
        "icon": "user",
        "url": "#",
        "file_path": "#",
        "params": "",
        "node": "#",
        "sort": 0,
        "status": 1,
        "create_by": 0,
        "create_at": "0000-00-00 00:00:00",
        "is_inner": false,
        "values": "",
        "show_slider": 1,
        "statusText": "使用中",
        "innerText": "导航",
        "fullUrl": "#",
        "children": [
          {
            "id": "149",
            "pid": 148,
            "title": "个人设置",
            "icon": "",
            "url": "account/setting/base",
            "file_path": "account/setting/base",
            "params": "",
            "node": "project/index/editpersonal",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "",
            "show_slider": 1,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "account/setting/base"
          },
          {
            "id": "150",
            "pid": 148,
            "title": "安全设置",
            "icon": "",
            "url": "account/setting/security",
            "file_path": "account/setting/security",
            "params": "",
            "node": "project/index/editpersonal",
            "sort": 0,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": true,
            "values": "",
            "show_slider": 1,
            "statusText": "使用中",
            "innerText": "内页",
            "fullUrl": "account/setting/security"
          }
        ]
      },
      {
        "id": "125",
        "pid": 124,
        "title": "成员管理",
        "icon": "unlock",
        "url": "#",
        "file_path": "#",
        "params": "",
        "node": "#",
        "sort": 10,
        "status": 1,
        "create_by": 0,
        "create_at": "0000-00-00 00:00:00",
        "is_inner": false,
        "values": "",
        "show_slider": 0,
        "statusText": "使用中",
        "innerText": "导航",
        "fullUrl": "#",
        "children": [
          {
            "id": "126",
            "pid": 125,
            "title": "账号列表",
            "icon": "",
            "url": "system/account",
            "file_path": "system/account",
            "params": "",
            "node": "project/account/index",
            "sort": 10,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "",
            "show_slider": 1,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "system/account"
          },
          {
            "id": "130",
            "pid": 125,
            "title": "访问授权",
            "icon": "",
            "url": "system/account/auth",
            "file_path": "system/account/auth",
            "params": "",
            "node": "project/auth/index",
            "sort": 20,
            "status": 1,
            "create_by": 0,
            "create_at": "0000-00-00 00:00:00",
            "is_inner": false,
            "values": "",
            "show_slider": 1,
            "statusText": "使用中",
            "innerText": "导航",
            "fullUrl": "system/account/auth"
          }
        ]
      }
    ]
  }
]
